[phases.setup]
nixPkgs = ['...', 'python312', 'uv']

[phases.install]
cmds = ["cd api && uv sync --locked --no-dev"]

[start]
cmd = "cd api && uv run gunicorn --bind 0.0.0.0:6644 --workers 2 --timeout 180 main:app"
