name: Docker Image CI for GHCR
on:
  workflow_dispatch:
jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE: ghcr.io/${{ github.repository }}
    steps:
      - name: Get latest release tag
        id: get_release
        run: |
          latest_tag=$(curl -s "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          echo "Latest Release Tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> "$GITHUB_OUTPUT"

      - uses: actions/checkout@v4
      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Build and push the image
        run: |
          IMAGE=$(echo "$IMAGE" | tr '[:upper:]' '[:lower:]')
          docker build -t "$IMAGE:latest" -t "$IMAGE:${{ steps.get_release.outputs.latest_tag }}-${{ github.sha }}" -f ./api/Dockerfile ./api
          docker push "$IMAGE:latest"
          docker push "$IMAGE:${{ steps.get_release.outputs.latest_tag }}-${{ github.sha }}"
